### ISSUE TITLE
proposition: move cache one level up, introduce EvalRenderer struct

### ISSUE THREAD

**Issue by klebediev** [variantdev/vals#4]
Hi!
1. While I was working on [helmfile + vals prototype](https://github.com/klebediev/helmfile/commit/ee145c0f64c37fab0c94d6b4aedf848c3d50588e?diff=unified) as a part of [helmfile#881](https://github.com/roboll/helmfile/issues/881)
I got an impression that given interface of vals don't use caching effectively enough: on each new `Eval()` call cache is recreated. 
So, what if we intorduce `EvalRenderer` object to vals api and each consecutive call of `EvalRenderer.Eval()` will use existing cache?

2. I see caching is implemented for each provider independently. What if we move caching one level up and decom caching for providers?

here is my [propotype with proposed changes](https://github.com/klebediev/vals/commit/85b135c59bcae725cb4d9a888cd8d6aa38a8c002?diff=split)

**Comment by mumoshu** [comment]
@klebediev Hey! I'm super excited to see you're trying to work on the integration yourself!

Yeah this proposal makes a lot of sense.

For 1, I'd suggest something that doesn't get duplicated/conflict with the name `Eval` - how about `Runtime` instead of `EvanRendered` that can be created and used like the below would work?

```
r := vals.New(someOpts)
res, err := r.Eval(conf)
```

2 also makes sense. I think there's no prob just moving the logic upwards and remove caching from each provider.

**Comment by mumoshu** [comment]
Or maybe `Store` meaning "values store". Even in that case, the usage would remain the same as:

```
r := vals.New(someOpts)
res, err := r.Eval(conf)
```

**Comment by klebediev** [comment]
Thanks for your feedback @mumoshu !
