### ISSUE TITLE
Retriving multiple parameters by path from SSM fails

### ISSUE THREAD

**Issue by lucasslima** [variantdev/vals#78]
Hi,

I'm trying to retrieve multiple parameters based on path in SSM. Using the example provided in the README.md:
```
NAME        VALUE
/foo/bar    {"BAR":"VALUE"}
/foo/bar/a  A
/foo/bar/b  B
```
What I'm trying to do is assign:
```
foo: ref+awsssm://foo?recursive=true
```
And have the following result:
```
foo:
  bar:
     a: A
     b: B
```

Right now, when I try it I'm getting a error like:
```
expand awsssm://foo?recursive=true: get parameter: ParameterNotFound:
```
 Is doing this possible? If not, I would be happy to send the PR if there's some basic guidance on how to make the changes.

Thanks for the great work!

**Comment by mumoshu** [comment]
@lucasslima Hey! This might need a significant code change, as currently vals is designed to evaluate any single ref URL into a string value, not an object.

https://github.com/variantdev/vals/blob/master/vals.go#L294-L314

To clarify, the point of using `recursive=true` is to provide an alternative basis to scape the value at the key denoted by `#/path/to/value`.

Without recursive, ex. `ref+awsssm://foo`, vals assumes that the SSM key `foo` contains either a single value, or an a encoded JSON object that looks like `{"a":{"b":"B"}}`. For the latter case, where you can scrape the value further by `#/a/b` to finally turn `foo: ref+awsssm://foo?recursive=true` into `foo: B`. 

With recursive, ex. `foo: ref+awsssm://foo?recursive=true`, vals assumes that the SSM key `foo` is the prefix of some child keys and tries to build an object to be scraped. In this mode, you need to provide `#/path/to/key` to enforce the use of GetParametersByPath SSM API, because otherwise there's nothing to scrape when vals has no other choice chan using `GetParameter`, wich results in the error you mentioned.

**Comment by lucasslima** [comment]
Thanks for the response @mumoshu. I guess it would make things more complicated having the behavior I've mentioned. At least understanding that vals should only return strings makes me understand it a little better. I've changed my usage to address this.

Closing this then!
